// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v4.25.3
// source: proto/txn.proto

package seata_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartGlobalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	Mode          string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`       // saga|tcc|xa|msg|outbox|workflow
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // user-defined
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGlobalRequest) Reset() {
	*x = StartGlobalRequest{}
	mi := &file_proto_txn_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGlobalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGlobalRequest) ProtoMessage() {}

func (x *StartGlobalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGlobalRequest.ProtoReflect.Descriptor instead.
func (*StartGlobalRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{0}
}

func (x *StartGlobalRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *StartGlobalRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *StartGlobalRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type StartGlobalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartGlobalResponse) Reset() {
	*x = StartGlobalResponse{}
	mi := &file_proto_txn_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartGlobalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartGlobalResponse) ProtoMessage() {}

func (x *StartGlobalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartGlobalResponse.ProtoReflect.Descriptor instead.
func (*StartGlobalResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{1}
}

func (x *StartGlobalResponse) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type SubmitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_proto_txn_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_proto_txn_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{3}
}

type AbortRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortRequest) Reset() {
	*x = AbortRequest{}
	mi := &file_proto_txn_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortRequest) ProtoMessage() {}

func (x *AbortRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortRequest.ProtoReflect.Descriptor instead.
func (*AbortRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{4}
}

func (x *AbortRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type AbortResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbortResponse) Reset() {
	*x = AbortResponse{}
	mi := &file_proto_txn_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbortResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbortResponse) ProtoMessage() {}

func (x *AbortResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbortResponse.ProtoReflect.Descriptor instead.
func (*AbortResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{5}
}

type AddBranchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBranchRequest) Reset() {
	*x = AddBranchRequest{}
	mi := &file_proto_txn_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBranchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBranchRequest) ProtoMessage() {}

func (x *AddBranchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBranchRequest.ProtoReflect.Descriptor instead.
func (*AddBranchRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{6}
}

func (x *AddBranchRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *AddBranchRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *AddBranchRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type AddBranchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBranchResponse) Reset() {
	*x = AddBranchResponse{}
	mi := &file_proto_txn_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBranchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBranchResponse) ProtoMessage() {}

func (x *AddBranchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBranchResponse.ProtoReflect.Descriptor instead.
func (*AddBranchResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{7}
}

type BranchTryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchTryRequest) Reset() {
	*x = BranchTryRequest{}
	mi := &file_proto_txn_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchTryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchTryRequest) ProtoMessage() {}

func (x *BranchTryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchTryRequest.ProtoReflect.Descriptor instead.
func (*BranchTryRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{8}
}

func (x *BranchTryRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *BranchTryRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

func (x *BranchTryRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type BranchTryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchTryResponse) Reset() {
	*x = BranchTryResponse{}
	mi := &file_proto_txn_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchTryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchTryResponse) ProtoMessage() {}

func (x *BranchTryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchTryResponse.ProtoReflect.Descriptor instead.
func (*BranchTryResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{9}
}

type BranchStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	BranchId      string                 `protobuf:"bytes,2,opt,name=branch_id,json=branchId,proto3" json:"branch_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchStateRequest) Reset() {
	*x = BranchStateRequest{}
	mi := &file_proto_txn_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchStateRequest) ProtoMessage() {}

func (x *BranchStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchStateRequest.ProtoReflect.Descriptor instead.
func (*BranchStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{10}
}

func (x *BranchStateRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

func (x *BranchStateRequest) GetBranchId() string {
	if x != nil {
		return x.BranchId
	}
	return ""
}

type BranchStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BranchStateResponse) Reset() {
	*x = BranchStateResponse{}
	mi := &file_proto_txn_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BranchStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BranchStateResponse) ProtoMessage() {}

func (x *BranchStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BranchStateResponse.ProtoReflect.Descriptor instead.
func (*BranchStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{11}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gid           string                 `protobuf:"bytes,1,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_txn_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{12}
}

func (x *GetRequest) GetGid() string {
	if x != nil {
		return x.Gid
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnJson       []byte                 `protobuf:"bytes,1,opt,name=txn_json,json=txnJson,proto3" json:"txn_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_txn_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{13}
}

func (x *GetResponse) GetTxnJson() []byte {
	if x != nil {
		return x.TxnJson
	}
	return nil
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         uint32                 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint32                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_txn_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{14}
}

func (x *ListRequest) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListRequest) GetOffset() uint32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TxnJson       [][]byte               `protobuf:"bytes,1,rep,name=txn_json,json=txnJson,proto3" json:"txn_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_txn_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_txn_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_txn_proto_rawDescGZIP(), []int{15}
}

func (x *ListResponse) GetTxnJson() [][]byte {
	if x != nil {
		return x.TxnJson
	}
	return nil
}

var File_proto_txn_proto protoreflect.FileDescriptor

const file_proto_txn_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/txn.proto\x12\fseata.txn.v1\"T\n" +
	"\x12StartGlobalRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"'\n" +
	"\x13StartGlobalResponse\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\"!\n" +
	"\rSubmitRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\"\x10\n" +
	"\x0eSubmitResponse\" \n" +
	"\fAbortRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\"\x0f\n" +
	"\rAbortResponse\"Y\n" +
	"\x10AddBranchRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\x13\n" +
	"\x11AddBranchResponse\"Y\n" +
	"\x10BranchTryRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\x13\n" +
	"\x11BranchTryResponse\"C\n" +
	"\x12BranchStateRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\x12\x1b\n" +
	"\tbranch_id\x18\x02 \x01(\tR\bbranchId\"\x15\n" +
	"\x13BranchStateResponse\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03gid\x18\x01 \x01(\tR\x03gid\"(\n" +
	"\vGetResponse\x12\x19\n" +
	"\btxn_json\x18\x01 \x01(\fR\atxnJson\"S\n" +
	"\vListRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\rR\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\rR\x06offset\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\")\n" +
	"\fListResponse\x12\x19\n" +
	"\btxn_json\x18\x01 \x03(\fR\atxnJson2\xaf\x05\n" +
	"\x12TransactionService\x12R\n" +
	"\vStartGlobal\x12 .seata.txn.v1.StartGlobalRequest\x1a!.seata.txn.v1.StartGlobalResponse\x12C\n" +
	"\x06Submit\x12\x1b.seata.txn.v1.SubmitRequest\x1a\x1c.seata.txn.v1.SubmitResponse\x12@\n" +
	"\x05Abort\x12\x1a.seata.txn.v1.AbortRequest\x1a\x1b.seata.txn.v1.AbortResponse\x12L\n" +
	"\tAddBranch\x12\x1e.seata.txn.v1.AddBranchRequest\x1a\x1f.seata.txn.v1.AddBranchResponse\x12L\n" +
	"\tBranchTry\x12\x1e.seata.txn.v1.BranchTryRequest\x1a\x1f.seata.txn.v1.BranchTryResponse\x12T\n" +
	"\rBranchSucceed\x12 .seata.txn.v1.BranchStateRequest\x1a!.seata.txn.v1.BranchStateResponse\x12Q\n" +
	"\n" +
	"BranchFail\x12 .seata.txn.v1.BranchStateRequest\x1a!.seata.txn.v1.BranchStateResponse\x12:\n" +
	"\x03Get\x12\x18.seata.txn.v1.GetRequest\x1a\x19.seata.txn.v1.GetResponse\x12=\n" +
	"\x04List\x12\x19.seata.txn.v1.ListRequest\x1a\x1a.seata.txn.v1.ListResponseB!Z\x1fgithub.com/dtm-labs/seata-protob\x06proto3"

var (
	file_proto_txn_proto_rawDescOnce sync.Once
	file_proto_txn_proto_rawDescData []byte
)

func file_proto_txn_proto_rawDescGZIP() []byte {
	file_proto_txn_proto_rawDescOnce.Do(func() {
		file_proto_txn_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_txn_proto_rawDesc), len(file_proto_txn_proto_rawDesc)))
	})
	return file_proto_txn_proto_rawDescData
}

var file_proto_txn_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_txn_proto_goTypes = []any{
	(*StartGlobalRequest)(nil),  // 0: seata.txn.v1.StartGlobalRequest
	(*StartGlobalResponse)(nil), // 1: seata.txn.v1.StartGlobalResponse
	(*SubmitRequest)(nil),       // 2: seata.txn.v1.SubmitRequest
	(*SubmitResponse)(nil),      // 3: seata.txn.v1.SubmitResponse
	(*AbortRequest)(nil),        // 4: seata.txn.v1.AbortRequest
	(*AbortResponse)(nil),       // 5: seata.txn.v1.AbortResponse
	(*AddBranchRequest)(nil),    // 6: seata.txn.v1.AddBranchRequest
	(*AddBranchResponse)(nil),   // 7: seata.txn.v1.AddBranchResponse
	(*BranchTryRequest)(nil),    // 8: seata.txn.v1.BranchTryRequest
	(*BranchTryResponse)(nil),   // 9: seata.txn.v1.BranchTryResponse
	(*BranchStateRequest)(nil),  // 10: seata.txn.v1.BranchStateRequest
	(*BranchStateResponse)(nil), // 11: seata.txn.v1.BranchStateResponse
	(*GetRequest)(nil),          // 12: seata.txn.v1.GetRequest
	(*GetResponse)(nil),         // 13: seata.txn.v1.GetResponse
	(*ListRequest)(nil),         // 14: seata.txn.v1.ListRequest
	(*ListResponse)(nil),        // 15: seata.txn.v1.ListResponse
}
var file_proto_txn_proto_depIdxs = []int32{
	0,  // 0: seata.txn.v1.TransactionService.StartGlobal:input_type -> seata.txn.v1.StartGlobalRequest
	2,  // 1: seata.txn.v1.TransactionService.Submit:input_type -> seata.txn.v1.SubmitRequest
	4,  // 2: seata.txn.v1.TransactionService.Abort:input_type -> seata.txn.v1.AbortRequest
	6,  // 3: seata.txn.v1.TransactionService.AddBranch:input_type -> seata.txn.v1.AddBranchRequest
	8,  // 4: seata.txn.v1.TransactionService.BranchTry:input_type -> seata.txn.v1.BranchTryRequest
	10, // 5: seata.txn.v1.TransactionService.BranchSucceed:input_type -> seata.txn.v1.BranchStateRequest
	10, // 6: seata.txn.v1.TransactionService.BranchFail:input_type -> seata.txn.v1.BranchStateRequest
	12, // 7: seata.txn.v1.TransactionService.Get:input_type -> seata.txn.v1.GetRequest
	14, // 8: seata.txn.v1.TransactionService.List:input_type -> seata.txn.v1.ListRequest
	1,  // 9: seata.txn.v1.TransactionService.StartGlobal:output_type -> seata.txn.v1.StartGlobalResponse
	3,  // 10: seata.txn.v1.TransactionService.Submit:output_type -> seata.txn.v1.SubmitResponse
	5,  // 11: seata.txn.v1.TransactionService.Abort:output_type -> seata.txn.v1.AbortResponse
	7,  // 12: seata.txn.v1.TransactionService.AddBranch:output_type -> seata.txn.v1.AddBranchResponse
	9,  // 13: seata.txn.v1.TransactionService.BranchTry:output_type -> seata.txn.v1.BranchTryResponse
	11, // 14: seata.txn.v1.TransactionService.BranchSucceed:output_type -> seata.txn.v1.BranchStateResponse
	11, // 15: seata.txn.v1.TransactionService.BranchFail:output_type -> seata.txn.v1.BranchStateResponse
	13, // 16: seata.txn.v1.TransactionService.Get:output_type -> seata.txn.v1.GetResponse
	15, // 17: seata.txn.v1.TransactionService.List:output_type -> seata.txn.v1.ListResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_proto_txn_proto_init() }
func file_proto_txn_proto_init() {
	if File_proto_txn_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_txn_proto_rawDesc), len(file_proto_txn_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_txn_proto_goTypes,
		DependencyIndexes: file_proto_txn_proto_depIdxs,
		MessageInfos:      file_proto_txn_proto_msgTypes,
	}.Build()
	File_proto_txn_proto = out.File
	file_proto_txn_proto_goTypes = nil
	file_proto_txn_proto_depIdxs = nil
}
